### ISSUE TITLE
How to send MS Band data directly to FitBit "online storage"?

### ISSUE THREAD

**Issue by mediaexplorer74** [programit/BandToFitbit#1]
Hi ) I'm still using my old MS Band 2 device :) MS Health web service was died/disabled few years ago...
Today I suddenly found your cool src code...
Please tell me (if you can) how to send MS Band data directly to FitBit "online storage"? :)
I'm trying to create the simplesst app (UWP- or Xamarin Forms-based) for my old sweet WinPhone (Lumia 950).

Best,
m.e.

**Comment by programit** [comment]
Unfortunately this project was pulling form MS Health API. Now that, that APIis gone as you said, this project will no longer work. I don't have a Band anymore so I don't think I could even help try out new solutions. Best of luck!
